const products = [
    {
        image: "../src/images/playstation-5.jpg",
        name: "Sony Playstation 5",
        description: "Experimente una carga ultrarrápida con un SSD de ultra alta velocidad, una inmersión más profunda con soporte para retroalimentación háptica, activadores adaptativos y audio 3D, y una generación completamente nueva de increíbles juegos de PlayStation.",
        price: 499.99,
        stock: 5,
    },
    {
        image: "../src/images/iphone-13-pro.jpeg",
        name: "Apple iPhone 13 Pro",
        description: "Un sistema de cámara mucho más potente. Una pantalla Super Retina XDR más brillante y vívida con ProMotion. El chip más rápido en un teléfono inteligente. Durabilidad excepcional. La capacidad de grabar en ProRAW. Y un gran salto en la duración de la batería.",
        price: 999.99,
        stock: 10,
    },
    {
        image: "../src/images/samsung-qled-8k-tv.jpg",
        name: "Samsung QLED 8K TV",
        description: "La impresionante belleza del mundo vista a través de la pantalla más novedosa. Con una resolución de 8K, escalado inteligente impulsado por IA y un volumen de color del 100 % con tecnología Quantum Dot, este televisor te transporta a una nueva dimensión de la realidad.",
        price: 2999.99,
        stock: 2,
    },
    {
        image: "../src/images/amazon-kindle.jpg",
        name: "Amazon Kindle Paperwhite",
        description: "El Kindle Paperwhite más delgado y liviano hasta el momento, con un diseño frontal al ras y una pantalla sin reflejos de 300 ppp que se lee como papel real, incluso bajo la luz del sol. Ahora resistente al agua, para que puedas leer y relajarte en la playa, junto a la piscina o en el baño.",
        price: 129.99,
        stock: 15,
    },
    {
        image: "../src/images/bose-quietcomfort.png",
        name: "Auriculares Bose QuietComfort 35 II",
        description: "Los auriculares inalámbricos QuietComfort 35 II están diseñados con una cancelación de ruido de primer nivel. Y ahora son aún mejores. Con su Asistente de Google y Amazon Alexa incorporados, puede controlar la música, enviar y recibir mensajes de texto y obtener respuestas usando solo su voz.",
        price: 299.99,
        stock: 8,
    },
    {
        image: "../src/images/dyson-vacuum.jpg",
        name: "Aspiradora Dyson V15 Detect",
        description: "La única aspiradora que detecta y se adapta automáticamente a su tipo de piso, elimina la suciedad y el polvo microscópico de todos los tipos de piso y limpia profundamente en cualquier lugar. Hasta 60 minutos de tiempo de ejecución. La pantalla LCD muestra la cuenta regresiva del tiempo de ejecución y el rendimiento de la máquina en tiempo real.",
        price: 699.99,
        stock: 3,
    },
    {
        image: "../src/images/canon-camera.jpg",
        name: "Cámara Canon EOS R5",
        description: "Para el creador de imágenes profesional que necesita capacidades de resolución, velocidad y video, está la Canon EOS R5. Esta cámara sin espejo de fotograma completo establece un nuevo estándar de versatilidad y cuenta con un sensor CMOS de 45 MP recientemente desarrollado y grabación de video RAW de 8K.",
        price: 3899.99,
        stock: 1,
    },
];
